import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Link from 'next/link';

export default function Home() {
  return (
    <>
      <Head>
        <title>Chinwizu auction dapp</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
      <div className={styles.home}>
        <div className={styles.home_left}>
          <h2 className={styles.heading}>Sell that item by raising an auction
              on this awesome platform
          </h2>
          <p>We provide you the opportunity to raise an auction to sell
            those items you've always wanted the world to see and appreciate. 
            Our numerous users are happy and eager to bid for them. <b>Bid with $cUsd and earn $NwizuGold</b>
          </p>
          <Link href='/listing'><button className={styles.btn}>List an Item</button></Link>
        </div>
        <div className={styles.home_right}>
            <div className={styles.row_1}>
                <Image src='/../public/auction1.png' width={150} height={180}/>
                <Image src='/../public/auction2.png' width={150} height={180}/>
            </div>
            <div className={styles.row_2}>
                <Image src='/../public/auction3.jpeg' width={150} height={180}/>
                <Image src='/../public/auction4.jpeg' width={150} height={180}/>
            </div>
        </div>
    </div>
      

      </main>
    </>
  )
}
